apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synthetic-data-pvc
  namespace: synthetic-data
  labels:
    app: synthetic-data-mcp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd  # Adjust based on your cluster's storage classes
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: synthetic-data
  labels:
    app: synthetic-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: synthetic-data
  labels:
    app: synthetic-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: synthetic-data
  labels:
    app: synthetic-ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi  # Large models require significant storage
  storageClassName: standard  # Can use standard storage for model files